import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../utils/api";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

function Scanner() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const navigate = useNavigate();

  // Progress Bar Color
  const getScoreColor = (score) => {
    if (score >= 80) return "#22c55e";
    if (score >= 50) return "#f59e0b";
    return "#ef4444";
  };

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      navigate("/login");
    }
  }, [navigate]);

  const startScan = async () => {
    if (!url.trim()) {
      alert("Please enter a website URL to scan");
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const res = await api.post("/api/scans/add", { url: url.trim() });
      setResult(res.data);
      setUrl("");
    } catch (err) {
      console.error("Scan error:", err);
      alert(err.response?.data?.message || "Scan failed. Please check the URL and try again.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!result) return;

    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("AI Security Suite Report", 105, 20, {
      align: "center",
    });

    autoTable(doc, {
      startY: 35,
      head: [["Item", "Value"]],
      body: [
        ["Website", result.url || result.domain?.domain],
        ["Security Score", `${result.score}/100`],
        ["Risk Level", result.riskLevel],
        ["Status Code", result.statusCode || "N/A"],
        ["Response Time", `${result.responseTime || 0} ms`],
        ["SSL Status", result.ssl?.status || "N/A"],
        ["SSL Issuer", result.ssl?.issuer || "N/A"],
      ],
    });

    let y = doc.lastAutoTable.finalY + 15;

    doc.setFontSize(14);
    doc.text("Technology Detection", 14, y);

    y += 8;

    result.technologies?.forEach((tech) => {
      doc.text("• " + tech, 18, y);
      y += 7;
    });

    y += 8;

    doc.text("Vulnerabilities", 14, y);

    y += 8;

    (result.vulnerabilities || "")
      .split(",")
      .forEach((item) => {
        if (item.trim()) {
          doc.text("• " + item.trim(), 18, y);
          y += 7;
        }
      });

    y += 8;

    doc.text("Recommendations", 14, y);

    y += 8;

    result.recommendations?.forEach((item) => {
      doc.text("• " + item, 18, y);
      y += 7;
    });

    doc.setFontSize(11);
    doc.text("Generated by AI Security Suite", 105, 285, { align: "center" });

    doc.save(`Security_Report_${result.domain?.domain || "scan"}.pdf`);
  };

  return (
    <div
      style={{
        background: "#08142e",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        color: "white",
      }}
    >
      <Navbar />

      <main style={{ flex: 1, padding: "30px 40px" }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "25px",
            flexWrap: "wrap",
            gap: "15px",
          }}
        >
          <h1 style={{ margin: 0 }}>🛡 Live Vulnerability Scanner</h1>

          <div style={{ display: "flex", gap: "10px" }}>
            <button
              onClick={() => navigate("/dashboard")}
              style={{
                background: "#16a34a",
                color: "white",
                border: "none",
                padding: "10px 20px",
                borderRadius: "8px",
                cursor: "pointer",
                fontWeight: "bold",
              }}
            >
              📊 Dashboard
            </button>
            <button
              onClick={() => navigate("/history")}
              style={{
                background: "#2563eb",
                color: "white",
                border: "none",
                padding: "10px 20px",
                borderRadius: "8px",
                cursor: "pointer",
                fontWeight: "bold",
              }}
            >
              📜 Scan History
            </button>
          </div>
        </div>

        {/* Input Bar */}
        <div style={{ display: "flex", gap: "15px", flexWrap: "wrap", marginBottom: "25px" }}>
          <input
            type="text"
            placeholder="https://example.com"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && startScan()}
            style={{
              width: "480px",
              maxWidth: "100%",
              padding: "12px 16px",
              fontSize: "16px",
              borderRadius: "8px",
              border: "1px solid #2563eb50",
              background: "#10244d",
              color: "white",
            }}
          />

          <button
            onClick={startScan}
            disabled={loading}
            style={{
              padding: "12px 30px",
              background: loading ? "#60a5fa" : "#2563eb",
              color: "white",
              border: "none",
              borderRadius: "8px",
              cursor: loading ? "not-allowed" : "pointer",
              fontSize: "16px",
              fontWeight: "bold",
            }}
          >
            {loading ? "🔄 Scanning..." : "Start Scan"}
          </button>
        </div>

        {loading && (
          <div style={{ marginTop: "20px" }}>
            <h2 style={{ color: "#60a5fa" }}>🔄 Analyzing Target Website & Defensive Headers...</h2>
            <p style={{ color: "#94a3b8" }}>Testing SSL/TLS certificates, WHOIS registry, and security policies.</p>
          </div>
        )}

        {result && (
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              marginTop: "20px",
            }}
          >
            <div
              style={{
                background: "#10244d",
                padding: "35px",
                width: "100%",
                maxWidth: "1800px",
                borderRadius: "12px",
                boxShadow: "0 0 15px rgba(0,0,0,0.5)",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginBottom: "15px",
                  flexWrap: "wrap",
                  gap: "10px",
                }}
              >
                <h2 style={{ margin: 0 }}>📋 Security Audit Report: {result.url}</h2>

                <button
                  onClick={downloadPDF}
                  style={{
                    background: "#16a34a",
                    color: "white",
                    border: "none",
                    padding: "12px 24px",
                    borderRadius: "8px",
                    cursor: "pointer",
                    fontSize: "15px",
                    fontWeight: "bold",
                  }}
                >
                  ⬇ Download PDF Report
                </button>
              </div>

              <hr style={{ borderColor: "#1e3a8a40" }} />

              {/* Progress Bar */}
              <h3
                style={{
                  color: "#60a5fa",
                  fontSize: "24px",
                  marginBottom: "12px",
                }}
              >
                📊 Security Score
              </h3>

              <div
                style={{
                  width: "100%",
                  height: "28px",
                  background: "#1f2937",
                  borderRadius: "20px",
                  overflow: "hidden",
                }}
              >
                <div
                  style={{
                    width: `${result.score}%`,
                    height: "100%",
                    background: getScoreColor(result.score),
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                    color: "white",
                    fontWeight: "bold",
                    transition: "width 0.8s",
                  }}
                >
                  {result.score}%
                </div>
              </div>

              <div style={{ marginTop: "15px", fontSize: "16px", display: "flex", gap: "25px", flexWrap: "wrap" }}>
                <p>
                  <strong>Security Rating:</strong> {result.score}/100
                </p>
                <p>
                  <strong>Status:</strong> ✅ Scan Completed
                </p>
                <p>
                  <strong>Risk Level:</strong>{" "}
                  <span
                    style={{
                      color:
                        result.riskLevel === "Low"
                          ? "#22c55e"
                          : result.riskLevel === "Medium"
                          ? "#f59e0b"
                          : "#ef4444",
                      fontWeight: "bold",
                    }}
                  >
                    {result.riskLevel}
                  </span>
                </p>
              </div>

              <hr style={{ borderColor: "#1e3a8a40" }} />

              {/* AI Analysis Section */}
              {result.aiAnalysis && (
                <div
                  style={{
                    background: result.aiAnalysis.aiEnabled ? "#1e3a8a25" : "#1e293b40",
                    border: `1px solid ${result.aiAnalysis.aiEnabled ? "#3b82f6" : "#475569"}`,
                    padding: "20px",
                    borderRadius: "10px",
                    marginBottom: "25px",
                    marginTop: "15px",
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap" }}>
                    <h3 style={{ margin: 0, color: "#60a5fa", display: "flex", alignItems: "center", gap: "8px" }}>
                      🤖 AI Threat Assessment {result.aiAnalysis.aiEnabled && <span style={{ fontSize: "12px", background: "#2563eb", padding: "2px 8px", borderRadius: "12px" }}>Gemini 1.5 Flash</span>}
                    </h3>
                    <span style={{ fontSize: "13px", color: result.aiAnalysis.aiEnabled ? "#86efac" : "#94a3b8" }}>
                      {result.aiAnalysis.aiEnabled ? "● AI Analysis Active" : "○ AI Analysis Standby"}
                    </span>
                  </div>

                  {result.aiAnalysis.aiEnabled && result.aiAnalysis.insights ? (
                    <div style={{ marginTop: "12px", lineHeight: "26px", fontSize: "15px", whiteSpace: "pre-wrap" }}>
                      {result.aiAnalysis.insights}
                    </div>
                  ) : (
                    <p style={{ marginTop: "10px", color: "#94a3b8", fontSize: "14px", lineHeight: "22px" }}>
                      {result.aiAnalysis.message || "Set GEMINI_API_KEY in backend/.env to activate intelligent deep analysis."}
                    </p>
                  )}
                </div>
              )}

              {/* Vulnerabilities */}
              <h3 style={{ color: "#60a5fa", fontSize: "24px", marginBottom: "10px" }}>
                ⚠ Vulnerabilities & Missing Headers
              </h3>
              <p style={{ fontSize: "16px", lineHeight: "26px" }}>{result.vulnerabilities}</p>

              <hr style={{ borderColor: "#1e3a8a40" }} />

              {/* Recommendations */}
              <h3 style={{ color: "#60a5fa", fontSize: "24px", marginBottom: "10px" }}>
                🛡 Remediation Recommendations
              </h3>
              <ul>
                {result.recommendations?.map((item, index) => (
                  <li key={index} style={{ marginBottom: "8px", fontSize: "16px" }}>
                    {item}
                  </li>
                ))}
              </ul>

              <hr style={{ borderColor: "#1e3a8a40" }} />

              {/* Details Cards */}
              <div
                style={{
                  display: "flex",
                  gap: "20px",
                  flexWrap: "wrap",
                  marginTop: "25px",
                }}
              >
                {/* SSL Certificate */}
                <div
                  style={{
                    flex: "1",
                    minWidth: "300px",
                    background: "#18315f",
                    padding: "20px",
                    borderRadius: "10px",
                  }}
                >
                  <h3 style={{ color: "#60a5fa", fontSize: "22px", marginBottom: "15px" }}>🔒 SSL Certificate</h3>
                  <p><strong>📌 Status:</strong> {result.ssl?.status}</p>
                  <p><strong>🏢 Issuer:</strong> {result.ssl?.issuer}</p>
                  <p><strong>📅 Valid From:</strong> {result.ssl?.validFrom}</p>
                  <p><strong>📅 Valid To:</strong> {result.ssl?.validTo}</p>
                  <p><strong>⏳ Days Remaining:</strong> {result.ssl?.daysRemaining}</p>
                </div>

                {/* Technology Detection & Domain */}
                <div
                  style={{
                    flex: "1",
                    minWidth: "300px",
                    background: "#18315f",
                    padding: "20px",
                    borderRadius: "10px",
                  }}
                >
                  <h3 style={{ color: "#60a5fa", fontSize: "22px", marginBottom: "15px" }}>🖥 Technologies</h3>
                  <div>
                    {result.technologies?.map((tech, index) => (
                      <p key={index} style={{ margin: "6px 0" }}>✅ {tech}</p>
                    ))}
                  </div>

                  <hr style={{ borderColor: "#2563eb30", margin: "15px 0" }} />

                  <p><strong>🌐 Domain:</strong> {result.domain?.domain}</p>
                  <p><strong>🏢 Registrar:</strong> {result.domain?.registrar}</p>
                  <p><strong>🌍 Country:</strong> {result.domain?.country}</p>
                </div>

                {/* HTTP Information */}
                <div
                  style={{
                    flex: "1",
                    minWidth: "300px",
                    background: "#18315f",
                    padding: "20px",
                    borderRadius: "10px",
                  }}
                >
                  <h3 style={{ color: "#60a5fa", fontSize: "22px", marginBottom: "15px" }}>🌐 HTTP Information</h3>
                  <p><strong>📡 Status Code:</strong> {result.statusCode}</p>
                  <p><strong>⚡ Response Time:</strong> {result.responseTime} ms</p>
                  <p><strong>🔒 Protocol:</strong> {result.httpInfo?.protocol || "HTTPS"}</p>
                  <p><strong>🖥 Server:</strong> {result.httpInfo?.server || "Unknown"}</p>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>

      <Footer />
    </div>
  );
}

export default Scanner;